use clap::{CommandFactory, Parser, Subcommand, ValueEnum};
use gnosis_vpn_lib::command::Command as LibCommand;
use gnosis_vpn_lib::socket;
use std::path::PathBuf;

#[derive(Clone, Copy, Debug, ValueEnum)]
pub enum OutputFormat {
    Plain,
    Json,
    Yaml,
}

/// Gnosis VPN client control interface for Gnosis VPN service
#[derive(Debug, Parser)]
#[command(version)]
pub struct Cli {
    #[command(subcommand)]
    pub command: Command,

    /// Specify socket path
    #[arg(
        short,
        long,
        env = socket::root::ENV_VAR,
        default_value = socket::root::DEFAULT_PATH
    )]
    pub socket_path: PathBuf,

    /// Output format applied to every command
    #[arg(short = 'o', long = "output", value_name = "FORMAT", value_enum)]
    pub output: Option<OutputFormat>,
}

#[derive(Debug, Subcommand)]
pub enum Command {
    /// Query current service status
    #[command()]
    Status {},

    /// Connect to this exit location
    #[command()]
    Connect {
        /// Endpoint node address
        id: String,
    },

    /// Disconnect from current exit location
    #[command()]
    Disconnect {},

    /// Query balance information
    #[command()]
    Balance {},

    /// Trigger a refresh of node information including balance
    #[command()]
    RefreshNode {},

    /// Trigger a funding tool run to claim funds for your account during onboarding
    #[command()]
    FundingTool {
        /// Your secret hash
        secret: String,
    },

    /// Solicit a ping response ("pong") from the service and it's worker process to check if it is alive
    #[command()]
    Ping {},

    /// Trigger telemetry gathering from underlying edge client
    #[command()]
    Telemetry {},

    /// Query some nerd stats for connecting/connected destination
    #[command()]
    NerdStats {},

    /// Display service information, such as versions and file locations
    #[command()]
    Info {},

    /// Start worker process that runs main connection loop
    /// Needs a keep alive timeout to determine how long to wait for commands before stopping
    /// worker and returning to idle mode
    /// This timeout will be reset on every worker command.
    /// Commands not resetting the timeout are: Info, StopClient, Ping
    #[command()]
    StartClient {
        /// Keep alive timeout - stops worker when expired
        keep_alive: humantime::Duration,
    },

    /// Stop worker process to return to idle mode
    #[command()]
    StopClient {},

    /// Fetch and display the latest available version from the update manifest
    ///
    /// Refuses to run unless the VPN is connected. Pass --force to bypass the connection check.
    #[command()]
    CheckUpdate {
        /// Perform the connection even if VPN is currently inactive (insecure)
        #[arg(short = 'f', long)]
        force: bool,
    },

    /// Print shell completion script for the given shell to stdout
    #[command(hide = true)]
    Completions { shell: clap_complete::Shell },

    /// List configured destination IDs, one per line
    #[command(hide = true)]
    Destinations {},
}

impl From<Command> for LibCommand {
    fn from(val: Command) -> Self {
        match val {
            Command::Status {} => LibCommand::Status,
            Command::Connect { id } => LibCommand::Connect(id),
            Command::Disconnect {} => LibCommand::Disconnect,
            Command::Balance {} => LibCommand::Balance,
            Command::RefreshNode {} => LibCommand::RefreshNode,
            Command::FundingTool { secret } => LibCommand::FundingTool(secret),
            Command::Ping {} => LibCommand::Ping,
            Command::Telemetry {} => LibCommand::Telemetry,
            Command::NerdStats {} => LibCommand::NerdStats,
            Command::Info {} => LibCommand::Info,
            Command::StartClient { keep_alive } => LibCommand::StartClient(keep_alive.into()),
            Command::StopClient {} => LibCommand::StopClient,
            Command::Destinations {} => LibCommand::Destinations,
            Command::CheckUpdate { .. } => unreachable!("CheckUpdate is handled before socket dispatch"),
            Command::Completions { .. } => unreachable!("Completions is handled before socket dispatch"),
        }
    }
}

pub fn parse() -> Cli {
    Cli::parse()
}

pub fn generate_completions(shell: clap_complete::Shell) {
    clap_complete::generate(shell, &mut Cli::command(), "gnosis_vpn-ctl", &mut std::io::stdout());

    match shell {
        clap_complete::Shell::Fish => {
            // The helper __fish_gnosis_vpn_ctl_using_subcommand is generated by clap_complete above.
            // This line adds one dynamic completion rule on top of the static ones.
            print!(
                "\ncomplete -c gnosis_vpn-ctl \
                -n '__fish_gnosis_vpn_ctl_using_subcommand connect' \
                -a '(gnosis_vpn-ctl destinations 2>/dev/null)' \
                --no-files\n"
            );
        }
        clap_complete::Shell::Bash => {
            // Save the clap-generated function under a private name, then redefine
            // _gnosis_vpn-ctl to intercept the connect-id position with dynamic destinations.
            // Global flags (e.g. --socket-path) may appear before the connect subcommand,
            // so we locate connect by scanning COMP_WORDS instead of assuming index 1.
            print!(
                r#"
eval "_gnosis_vpn_ctl_clap() $(declare -f _gnosis_vpn-ctl | tail -n +2)"
_gnosis_vpn-ctl() {{
    local cur="${{COMP_WORDS[COMP_CWORD]}}"

    local connect_index=0
    local i
    for (( i=1; i<${{#COMP_WORDS[@]}}; i++ )); do
        if [[ "${{COMP_WORDS[i]}}" == "connect" ]]; then
            connect_index=$i
            break
        fi
    done

    if [[ $connect_index -gt 0 && $COMP_CWORD -eq $((connect_index+1)) && "$cur" != -* ]]; then
        local socket_args=()
        for (( i=1; i<connect_index; i++ )); do
            case "${{COMP_WORDS[i]}}" in
                --socket-path=*)
                    socket_args=(--socket-path "${{COMP_WORDS[i]#*=}}")
                    ;;
                --socket-path|-s)
                    if (( i+1 < connect_index )); then
                        socket_args=(--socket-path "${{COMP_WORDS[i+1]}}")
                    fi
                    ;;
            esac
        done
        local dests
        dests=$(gnosis_vpn-ctl "${{socket_args[@]}}" destinations 2>/dev/null)
        COMPREPLY=($(compgen -W "$dests" -- "$cur"))
        return
    fi
    _gnosis_vpn_ctl_clap "$@"
}}
"#
            );
        }
        clap_complete::Shell::Zsh => {
            // Use zsh's `functions` array to patch the connect id spec in-place:
            // replace _default (file completion) with a helper that calls `destinations`.
            print!(
                r#"
_gnosis_vpn_ctl_destinations() {{
    local -a dests
    dests=("${{(@f)$(gnosis_vpn-ctl destinations 2>/dev/null)}}")
    _describe 'destination' dests
}}
functions[_gnosis_vpn-ctl]=${{functions[_gnosis_vpn-ctl]//:id -- Endpoint node address:_default/:id -- Endpoint node address:_gnosis_vpn_ctl_destinations}}
"#
            );
        }
        _ => {}
    }
}
