###
# Gnosis VPN service configuration file
#
# On unix the default config path is `/etc/gnosisvpn/config.toml`
# However you can override this by using `GNOSISVPN_CONFIG_PATH` env var
###

version = 1

[hoprd_node]
# URL pointing to the API access of your hoprd node with scheme and port (e.g., `http://192.168.0.89:3001`)
endpoint = "<your hoprd node API endpoint>"
api_token = "<your hoprd node API token>"

# Container forwarded connection port – if your hoprd node runs inside a Docker container,
# this should match the forwarded UDP port into the container.
# Note: This is NOT your API port, which must be specified in the `endpoint` field.
# This port is an additional port used to establish the tunnel connection on your hoprd node.
# In general, if you want to establish a connection on a specific port, simply provide that port here.
internal_connection_port = 1422

# copy this section from https://gnosisvpn.com/servers
[connection]
destination = "<exit node peer id>"

[connection.path]
intermediates = ["<community relayer peer id"]
