###
# Gnosis VPN service configuration file
#
# On unix the default config path is `/etc/gnosisvpn/config.toml`
# However you can override this by using `GNOSISVPN_CONFIG_PATH` env var
###

version = 1

[hoprd_node]
# URL pointing to the API access of your hoprd node with scheme and port (e.g., `http://192.168.0.89:3001`)
endpoint = "http://192.168.0.89:3001"
api_token = "<your hoprd node API token>"

internal_connection_port = 1422

# copy this section from https://gnosisvpn.com/servers
[connection]
destination = "<exit node peer id>"

[connection.path]
intermediates = ["<community relayer peer id"]
