###
# Gnosis VPN service configuration file
#
# On unix the default config path is `/etc/gnosisvpn/config.toml`
# However you can override this by using `GNOSISVPN_CONFIG_PATH` env var
###

version = 2

[hoprd_node]
# URL pointing to the API access of your hoprd node with scheme and port (e.g., `http://192.168.0.89:3001`)
endpoint = "<your hoprd node API endpoint>"
api_token = "<your hoprd node API token>"

# Container forwarded connection port – if your hoprd node runs inside a Docker container,
# this should match the forwarded UDP port into the container.
# Note: This is NOT your API port, which must be specified in the `endpoint` field.
# This port is an additional port used to establish the tunnel connection on your hoprd node.
# In general, if you want to establish a connection on a specific port, simply provide that port here.
internal_connection_port = 1422
# general config file version

###
## destinations section - configure available target destinations
[destinations]

[destinations.12D3KooWMEXkxWMitwu9apsHmjgDZ7imVHgEsjXfcyZfrqYMYjW7]
meta = { location = "Germany" }
path = { intermediates = [
  "12D3KooWFUD4BSzjopNzEzhSi9chAkZXRKGtQJzU482rJnyd2ZnP",
] }

[destinations.12D3KooWBRB3y81TmtqC34JSd61uS8BVeUqWxCSBijD5nLhL6HU5]
meta = { location = "USA" }
path = { intermediates = [
  "12D3KooWQLTR4zdLyXToQGx3YKs9LJmeL4MKJ3KMp4rfVibhbqPQ",
] }

[destinations.12D3KooWGdcnCwJ3645cFgo4drvSN3TKmxQFYEZK7HMPA6wx1bjL]
meta = { location = "Spain" }
path = { intermediates = [
  "12D3KooWFnMnefPQp2k3XA3yNViBH4hnUCXcs9LasLUSv6WAgKSr",
] }

[wireguard]
listen_port = 51820
# only specify this if you want to manually connect via WireGuard
# manual_mode = { public_key = "<your WireGuard public key>" }
