###
# Gnosis VPN service configuration file
#
# On unix the default config path is `/etc/gnosisvpn/config.toml`
# However you can override this by using `GNOSISVPN_CONFIG_PATH` env var
###

# general config file version
version = 3

[hoprd_node]
# URL pointing to the API access of your hoprd node with scheme and port (e.g., `http://192.168.0.89:3001`)
endpoint = "<your hoprd node API endpoint>"
api_token = "<your hoprd node API token>"

# Container forwarded connection port – if your hoprd node runs inside a Docker container,
# this should match the forwarded UDP port into the container.
# Note: This is NOT your API port, which must be specified in the `endpoint` field.
# This port is an additional port used to establish the tunnel connection on your hoprd node.
# In general, if you want to establish a connection on a specific port, simply provide that port here.
internal_connection_port = 1422

###
## destinations section - configure available target destinations
[destinations]

[destinations.0xD9c11f07BfBC1914877d7395459223aFF9Dc2739]
meta = { location = "Germany" }
path = { intermediates = ["0xD88064F7023D5dA2Efa35eAD1602d5F5d86BB6BA"] }

[destinations.0xa5Ca174Ef94403d6162a969341a61baeA48F57F8]
meta = { location = "USA" }
path = { intermediates = ["0x25865191AdDe377fd85E91566241178070F4797A"] }

[destinations.0x8a6E6200C9dE8d8F8D9b4c08F86500a2E3Fbf254]
meta = { location = "Spain" }
path = { intermediates = ["0x2Cf9E5951C9e60e01b579f654dF447087468fc04"] }

###
## wireguard section - specific VPN-related settings

# [wireguard]
# If you want to disable WireGuard key rotation, provide a static private key here.
# force_private_key = "<your WireGuard private key>"
