# Sorts `Cargo.toml` dependencies. All other `.toml` files are formatted with the default config.
#
# https://taplo.tamasfe.dev/configuration/file.html#configuration-file

exclude = ["modules/**"]

[formatting]
reorder_keys = false

[[rule]]
include = ["*.toml", "**/Cargo.toml"]
keys = ["dependencies"]

[rule.formatting]
reorder_keys = true
