version = 2

[hoprd_node]
endpoint = "http://host.docker.internal:<api port>"
api_token = "<api token>"

[connection]
listen_host = "0.0.0.0:1422"
[connection.bridge]
target = "127.0.0.1:8000"
[connection.wg]
target = "127.0.0.1:51821"
[connection.ping]
address = "10.129.0.1"

[wireguard]
listen_port = 51822
# [wireguard.manual_mode]
# public_key = "/GKuptnmvVOWyxS4poOnkVaKHnxHDIJCR93HXX0yYT0="

[destinations."<peerid1>"]
meta = { location = "testpeerid1" }
path = { hops = 0 }

[destinations."<peerid2>"]
meta = { location = "testpeerid2" }
path = { hops = 0 }
