version = 1

[hoprd_node]
endpoint = "http://host.docker.internal:3011"
api_token = "e2e-API-token^^"
# internal_connection_port = 1422

[connection]
destination = "12D3KooWHc2LPyvYGLJbHoQeJUBXBjDRfMY7msobsPoWj8rCAGHr"
listen_host = "0.0.0.0:1422"
path.hop = 0
target.host = "127.0.0.1"
target.port = 51821
