version = 2

[hoprd_node]
endpoint = "http://host.docker.internal:<api port>"
api_token = "<api token>"

[connection]
listen_host = "0.0.0.0:1422"
[connection.wg]
target = "127.0.0.1:51821"

[wireguard]
listen_port = "<listen port>"

[destinations.<peer id>]
meta = { location = "local6" }
path = { hops = 0 }
