version = 2

[hoprd_node]
endpoint = "http://host.docker.internal:<api port>"
api_token = "<api token>"

[connection]
listen_host = "0.0.0.0:1422"
[connection.bridge]
target = "127.0.0.1:8000"
[connection.wg]
target = "127.0.0.1:51821"
[connection.ping]
address = "10.129.0.1"

[destinations."<address1>"]
meta = { location = "testnode5" }
path = { hops = 0 }

[destinations."<address2>"]
meta = { location = "testnode6" }
path = { hops = 0 }
