name: Build
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
      - labeled
concurrency:
  group: ${{ github.ref }}-build
  cancel-in-progress: true
permissions:
  contents: read
env:
  CARGO_TERM_COLOR: always
jobs:
  build-binaries:
    name: Binary ${{ matrix.architecture }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - architecture: x86_64-linux
            runner: depot-ubuntu-22.04-4 # Depot Ubuntu 22.04, 4 CPUs, 16 GB RAM
            build_command: nix build -L .#binary-gnosis_vpn-x86_64-linux
            build_debug_command: nix build -L .#binary-gnosis_vpn-x86_64-linux-dev
            required_label: ""
          - architecture: aarch64-linux
            runner: depot-ubuntu-22.04-arm-4 # Depot Ubuntu 22.04 ARM, 4 CPUs, 16 GB RAM
            build_command: nix build -L .#binary-gnosis_vpn-aarch64-linux
            build_debug_command: nix build -L .#binary-gnosis_vpn-aarch64-linux-dev
            required_label: "binary:aarch64-linux"
          - architecture: aarch64-darwin
            runner: depot-macos-15 # Depot Apple Silicon M2, 8 CPUs, 24 GB RAM, 400 GB SSD
            build_command: nix build -L .#binary-gnosis_vpn-aarch64-darwin
            build_debug_command: nix build -L .#binary-gnosis_vpn-aarch64-darwin-dev
            required_label: "binary:aarch64-darwin"
    uses: hoprnet/hopr-workflows/.github/workflows/build-binaries.yaml@ausias/adapt-gnosisvpn #build-binaries-v2
    permissions:
      contents: read
    with:
      source_branch: ${{ github.event.pull_request.head.ref || github.ref }}
      version_type: commit
      architecture: ${{ matrix.architecture }}
      cachix_cache_name: gnosis-vpn-client
      build_command: ${{ matrix.build_command }}
      build_debug_command: ${{ matrix.build_debug_command }}
      binary: gnosis_vpn
      runner: ${{ matrix.runner }}
      timeout_minutes: 240
      enabled: ${{ matrix.required_label == '' || contains(github.event.pull_request.labels.*.name, matrix.required_label) }}
    secrets:
      gcp_service_account: ${{ secrets.GCP_SA_GITHUB_ACTIONS }}
      cachix_auth_token: ${{ secrets.CACHIX_AUTH_TOKEN }}
      gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
      apple_certificate: ${{ secrets.APPLE_CERTIFICATE_DEVELOPER_P12_BASE64 }}
      apple_certificate_password: ${{ secrets.APPLE_CERTIFICATE_DEVELOPER_PASSWORD }}
  checks:
    name: Checks
    runs-on: depot-ubuntu-22.04-4
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Install Nix
        uses: cachix/install-nix-action@v31
      - name: Use Nix Cache
        uses: cachix/cachix-action@v17
        with:
          name: gnosis-vpn-client
        env:
          USER: runner
      - name: Run flake checks
        run: nix flake check -L --show-trace --max-jobs 1
  system-test:
    name: System tests
    runs-on: depot-ubuntu-22.04-4
    if: ${{ github.event.pull_request.head.repo.fork == false }}
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Setup Nix
        uses: hoprnet/hopr-workflows/actions/setup-nix@setup-nix-v1
        with:
          cachix_cache_name: gnosis-vpn-client
          cachix_auth_token: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Install system test dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wireguard-tools resolvconf
          echo "$USER ALL=(ALL) NOPASSWD: ALL" | sudo tee /etc/sudoers.d/nopasswd-runner
      - name: Install just
        uses: extractions/setup-just@v2
      - name: Build system service binaries
        run: |
          nix build .#binary-gnosis_vpn-dev
      - name: Build system test binary
        run: |
          nix build .#gnosis_vpn-test --out-link result-tests
      - name: Run the system test
        env:
          SYSTEM_TEST_HOPRD_ID: ${{ secrets.SYSTEM_TEST_HOPRD_ID }}
          SYSTEM_TEST_HOPRD_ID_PASSWORD: ${{ secrets.SYSTEM_TEST_HOPRD_ID_PASSWORD }}
          SYSTEM_TEST_SAFE: ${{ secrets.SYSTEM_TEST_SAFE }}
          SYSTEM_TEST_CONFIG: ${{ secrets.SYSTEM_TEST_CONFIG}}
          SYSTEM_TEST_WORKER_BINARY: ${{ github.workspace }}/result/bin/gnosis_vpn-worker
        run: just system-tests ${{ github.workspace }}/result-tests/bin/gnosis_vpn-system_tests
